"""
SQLAlchemy Database Models
--------------------------
User       — Account information
Prediction — Each PCOS detection result tied to a user
"""
import json
import hashlib
from datetime import datetime
from extensions import db


class User(db.Model):
    __tablename__ = "users"

    id           = db.Column(db.Integer, primary_key=True)
    name         = db.Column(db.String(100), nullable=False)
    email        = db.Column(db.String(120), unique=True, nullable=False)
    password_hash= db.Column(db.String(255), nullable=False)
    age          = db.Column(db.Integer, nullable=True)
    created_at   = db.Column(db.DateTime, default=datetime.utcnow)

    predictions  = db.relationship(
        "Prediction", backref="user", lazy=True, cascade="all, delete-orphan"
    )
    password_reset_tokens = db.relationship(
        "PasswordResetToken", backref="user", lazy=True, cascade="all, delete-orphan"
    )

    def to_dict(self):
        return {
            "id":         self.id,
            "name":       self.name,
            "email":      self.email,
            "age":        self.age,
            "created_at": self.created_at.isoformat() + "Z",
        }


class Prediction(db.Model):
    __tablename__ = "predictions"

    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    inputs     = db.Column(db.Text, nullable=False)   # JSON string of feature inputs
    result     = db.Column(db.String(20), nullable=False)  # "Positive" or "Negative"
    confidence = db.Column(db.Float, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def to_dict(self):
        return {
            "id":         self.id,
            "inputs":     json.loads(self.inputs),
            "result":     self.result,
            "confidence": self.confidence,
            "created_at": self.created_at.isoformat() + "Z",
        }


class DietPlan(db.Model):
    __tablename__ = "diet_plans"

    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    plan_data  = db.Column(db.Text, nullable=False) # JSON generated by AI
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def to_dict(self):
        return {
            "plan_data":  json.loads(self.plan_data),
            "created_at": self.created_at.isoformat() + "Z",
        }


class ChatHistory(db.Model):
    __tablename__ = "chat_history"

    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    role       = db.Column(db.String(50), nullable=False)  # "user" or "model"
    message    = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def to_dict(self):
        return {
            "id":         self.id,
            "role":       self.role,
            "message":    self.message,
            "created_at": self.created_at.isoformat() + "Z",
        }


class AwarenessTip(db.Model):
    __tablename__ = "awareness_tips"

    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    tips_data  = db.Column(db.Text, nullable=False)   # JSON array of tip strings
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def to_dict(self):
        return {
            "tips":       json.loads(self.tips_data),
            "created_at": self.created_at.isoformat() + "Z",
        }


class PasswordResetToken(db.Model):
    __tablename__ = "password_reset_tokens"

    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    token_hash = db.Column(db.String(64), unique=True, nullable=False, index=True)
    expires_at = db.Column(db.DateTime, nullable=False)
    used_at    = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    @staticmethod
    def hash_token(token):
        return hashlib.sha256(token.encode("utf-8")).hexdigest()

    def is_expired(self):
        return datetime.utcnow() > self.expires_at

    def is_usable(self):
        return self.used_at is None and not self.is_expired()
